# Generated by Django 2.0.2 on 2018-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.IntegerField()),
                ('light', models.FloatField()),
                ('humid', models.FloatField()),
            ],
        ),
    ]
